### ISSUE TITLE
Failure to log in with Github

### ISSUE THREAD

**Issue by MilesWK** [EnZon3/Drop#13]
When I went to log in, I pressed sign in, sign in with github, and then it takes me to a "Site not found" page. 
![image](https://github.com/EnZon3/Drop/assets/121042782/b4994044-01d8-4101-9195-44c0c1dde374)
I know Drop is still in development, so I wanted to help you if you don't know about this issue!

**Comment by boston2029** [comment]
Yeah it’s still in development, can y’all give him a break
________________________________
From: MilesWK ***@***.***>
Sent: Thursday, April 11, 2024 10:46:17 AM
To: EnZon3/Drop ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EnZon3/Drop] Failure to log in with Github (Issue #13)


When I went to log in, I pressed sign in, sign in with github, and then it takes me to a "Site not found" page.
image.png (view on web)<https://github.com/EnZon3/Drop/assets/121042782/b4994044-01d8-4101-9195-44c0c1dde374>
I know Drop is still in development, so I wanted to help you if you don't know about this issue!

**Comment by MilesWK** [comment]
> Yeah it’s still in development, can y’all give him a break

Oh I wasn't giving him any trouble. I just wanted to let him know that this existed. I assume he doesn't want to release it with an error.

**Comment by EnZon3** [comment]
Oh, sorry, my bad; the supabase instance paused over my mini hiatus, re-starting it now.

**Comment by EnZon3** [comment]
Speaking of which, I've been pretty inactive on this project due to some other side projects and homework taking up more of my time. I'll try to get some work done today.

**Comment by MilesWK** [comment]
Oh hey no problem. School first.
