### ISSUE TITLE
Sign up returns 404

### ISSUE THREAD

**Issue by Fairies-Feast** [EnZon3/Drop#3]
**Problem:** Sign up button redirects to /signup, which returns a `404 page not found`
**Steps to reproduce:**
1. Go to "https://drop-beta.vercel.app".
2. Press "Sign Up"

**Comment by boston2029** [comment]
Fam. See readme.md:
> Please note that this is a work in progress and is not yet ready for use.

**Comment by Fairies-Feast** [comment]
Yes, I saw that already

**Comment by EnZon3** [comment]
Haha, yea.. like I said it's just a shell and I'm trying to get most of the boilerplate done first before any functionality gets implemented. Am busy with quite a lot of stuff IRL so I can't work on this 24/7. Other than that, great catch 😆

**Comment by EnZon3** [comment]
Haha, yea.. like I said it's just a shell and I'm trying to get most of the boilerplate done first before any functionality gets implemented. Am busy with quite a lot of stuff IRL so I can't work on this 24/7. Other than that, great catch 😆
